name: CI/CD Pipeline
on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Generate simple IMAGE_TAG
        id: vars
        run: |
          IMAGE_TAG="v$(date +'%Y%m%d-%H%M')"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "Generated IMAGE_TAG: $IMAGE_TAG"
      
      - name: Build and push images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            gustaavolp/nginx-helloworld:${{ steps.vars.outputs.IMAGE_TAG }}
            gustaavolp/nginx-helloworld:latest

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update deployment image tag
        run: |
          sed -i 's|gustaavolp/nginx-helloworld:[^[:space:]]*|gustaavolp/nginx-helloworld:${{ needs.build-and-push.outputs.image-tag }}|g' k8s/deployment.yaml
          
          echo "Tag atualizada para: ${{ needs.build-and-push.outputs.image-tag }}"
      
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if git diff --quiet k8s/deployment.yaml; then
            echo "Nenhuma mudança no deployment.yaml"
            exit 0
          fi
          
          git add k8s/deployment.yaml
          git commit -m "update: image tag to ${{ needs.build-and-push.outputs.image-tag }}"
          git push origin main
